[colors]
ansi = [
    "#371c1b",
    "#a23c38",
    "#e46c67",
    "#5cc7d6",
    "#c8cc66",
    "#ec9693",
    "#96dee9",
    "#f3f2f2",
]
background = "#291514"
brights = [
    "#756161",
    "#a23c38",
    "#e46c67",
    "#5cc7d6",
    "#c8cc66",
    "#ec9693",
    "#96dee9",
    "#f3f2f2",
]
compose_cursor = "#f3f2f2"
cursor_bg = "#f3f2f2"
cursor_border = "#f3f2f2"
cursor_fg = "#291514"
foreground = "#f3f2f2"
scrollbar_thumb = "#371c1b"
selection_bg = "#371c1b"
selection_fg = "#b6afaf"
split = "#756161"
visual_bell = "#371c1b"

[colors.indexed]
16 = "#5cc7d6"
17 = "#f3f2f2"

[colors.tab_bar]
background = "#291514"
inactive_tab_edge = "#371c1b"

[colors.tab_bar.active_tab]
bg_color = "#e46c67"
fg_color = "#251918"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#291514"
fg_color = "#f3f2f2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#291514"
fg_color = "#f3f2f2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#371c1b"
fg_color = "#f3f2f2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#756161"
fg_color = "#f3f2f2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
